const ACCESS_TOKEN_HEADER_KEY = 'X-Access-Token'
const ACCESS_TOKEN_PROP = 'accessToken'
const REQUEST_ACCESS_TOKEN_HEADER_KEY = 'x-access-token'

const EXPOSE_HEADERS = {
  HEADER_KEY: 'Access-Control-Expose-Headers',
  HEADER_VALUE: [ACCESS_TOKEN_HEADER_KEY]
}

const CUSTOM_HEADERS = [
  {
    HEADER_KEY: ACCESS_TOKEN_HEADER_KEY,
    HEADER_PROP: ACCESS_TOKEN_PROP
  }
]

export default {
  EXPOSE_HEADERS,
  CUSTOM_HEADERS,
  ACCESS_TOKEN_PROP,
  ACCESS_TOKEN_HEADER_KEY,
  REQUEST_ACCESS_TOKEN_HEADER_KEY
}
